name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: Write value to Properties-file
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './webapp/src/main/resources/application.properties'
          property: |
            'server.port'
            'spring.datasource.url'
            'spring.datasource.username'
            'spring.datasource.password'
            'spring.datasource.driver-class-name'
          value: |
            ${{ secrets.SERVER_PORT }}
            ${{ secrets.DATASOURCE_URL }}
            ${{ secrets.DB_USERNAME }}
            ${{ secrets.DB_PASSWORD }}
            ${{ secrets.DRIVER_CLASS }}
      
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: ${{ secrets.SQL_HOST_PORT }}
          mysql database: ${{ secrets.DB_NAME }}
          mysql user: ${{ secrets.DB_USERNAME }}
          mysql password: ${{ secrets.DB_PASSWORD }}
          
      - name: Build with Maven
        run: mvn -f /home/runner/work/webapp/webapp/webapp/pom.xml clean install

      - name: Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ami-config.pkr.hcl
      
      - name: Packer Validate
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ami-config.pkr.hcl

      - uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: -var=AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} -var=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          target: ami-config.pkr.hcl