name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set path to maven
        id: mvn_path
        run: |
          echo "/opt/maven/bin" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn clean install
