name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          mysql database: 'webapp_cloud'
          mysql user: 'root'
          mysql password: 'Avengers2232@'
          
      - name: Build with Maven
        run: mvn -f /home/runner/work/webapp/webapp/webapp/pom.xml clean install

      - run: mkdir staging && cp target/*jar-with-dependencies.jar staging
        - uses: actions/upload-artifact@v1
          with:
            name: Package
            path: staging

      - name: Packer Init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ami-config.pkr.hcl
      
      - name: Packer Validate
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ami-config.pkr.hcl